banquetBuddy/banquetBuddy/settings.py
banquetBuddy/banquetBuddy/urls.py
banquetBuddy/core/templates/core/aboutus.html
banquetBuddy/core/templates/core/base.html
banquetBuddy/core/urls.py
banquetBuddy/core/views.py

About us page created with css styles. Close #4

feat: Created about us page

---

banquetBuddy/core/templates/core/base.html
banquetBuddy/core/urls.py

An error in the links of the Subscription page has been fixed

fix:fixed Subscription page

---

.gitignore
banquetBuddy/catering_employees/tests.py
banquetBuddy/catering_owners/models.py
banquetBuddy/core/models.py
banquetBuddy/core/templates/core/base.html
banquetBuddy/core/templates/core/notifications.html
banquetBuddy/core/tests.py
banquetBuddy/core/urls.py
banquetBuddy/core/views.py

Se ha implementado el sistema de notificaciones para los particulares
NOTA: Las notificaciones para empresas y empleados se implementaran al realizar la tarea: R-011 Notificaciones así como el indicador de que hay notificaciones
Para probar los cambios:
1.  crear un evento mediante la pestaña de  admin de django o mediante cualquier otro medio, dicho evento tiene que ocurrir en una semana o menos de la fecha actual
2. logearse con el particular asociado a dicho evento
3. Comprobar en la campana del header que al entrar se ve una notificacion.
4. volver al menu principal, volver a entrar en la pestaña de notificaciones y comprobar que la notificacion ya no se ve al haber sido ya leida.
Closes #111

Feature/notificaciones y recordatorios #111

---

banquetBuddy/catering_owners/templates/registro_company.html
banquetBuddy/core/templates/core/base.html
banquetBuddy/core/templates/core/privacy_policy.html
banquetBuddy/core/templates/core/registro_empleado.html
banquetBuddy/core/templates/core/registro_particular.html
banquetBuddy/core/templates/core/terms_and_conditions.html
banquetBuddy/core/urls.py
banquetBuddy/core/views.py

1. Se han agregado enlaces a las páginas de Política de Privacidad y Términos y Condiciones en el **footer** de la aplicación. 
2. Se ha implementado una funcionalidad que requiere que los usuarios acepten la Política de Privacidad y los Términos y Condiciones al registrarse en la aplicación. 
Se ha incluido un texto completo y detallado de ambas políticas, siguiendo las mejores prácticas y requisitos legales. La funcionalidad implementada asegura que los usuarios revisen y acepten las políticas antes de completar el registro, así como siempre las tendrán disponibles en el pie de la página.

feat: Add Privacy Policy and Terms and Conditions

---

banquetBuddy/catering_owners/forms.py
banquetBuddy/catering_owners/models.py
banquetBuddy/catering_owners/templates/add_plate.html
banquetBuddy/catering_owners/templates/edit_plate.html
banquetBuddy/catering_owners/templates/list_plates.html
banquetBuddy/catering_owners/urls.py
banquetBuddy/catering_owners/views.py
banquetBuddy/core/templates/core/profile.html
banquetBuddy/populate_db.py

Este Pull Request introduce una funcionalidad completa para la gestión de platos. La nueva característica permite a los usuarios de compañías de catering añadir, editar, y eliminar platos de su catálogo. 
Los cambios incluyen:
- Creación de formularios y vistas para añadir, editar y listar platos.
- Implementación de filtrado por menús asociados(para ver los platos de un menú en concreto) y funcionalidad de ordenación en la vista de listado de platos.
- Integración de paginación en la lista de platos.
- Modificaciones en el script de población de la base de datos para incluir la creación de platos.
**Al haber cambiado el modelo, es importante actualizar la base de datos en local. Para eso ejecutamos los scripts en orden:**
1) python delete_all_tables_database.py
2) python …

feat: Implement Plate Management

---

.github/workflows/changelog.yml
changelogs/1.0.0/CHANGELOG.md
requirements.txt

Se ha creado un nuevo workflow (**changelog.yml**) que automatiza la creación de changelogs a la hora de crear releases.
Se ha creado una carpeta **changelogs** donde se almacenarán los CHANGELOG.md correspondientes a cada release.
Además se ha creado el **CHANGELOG.md** correspondiente a la release pasada.
Se ha actualizado el **requirements.txt** con la dependencia necesaria para crear changelogs.
Si surge un problema al lanzarse el flujo de trabajo al crear una nueva release y no hay tiempo para solucionarlo, existe la opción de generar el archivo CHANGELOG.md localmente. Los pasos para hacerlo son los siguientes:
1. Actualizar el repositorio local con los cambios del repositorio remoto donde se creó la nueva release.
2. Ejecutar el comando **pip install -r requirements.tx**t para …

feat: Changelogs automation

---

changelogs/2.0.0/CHANGELOG.md

Se ha creado el changelog para el Sprint 2. Esto se hizo porque, según se menciona en la Pull Request #155 , había una posibilidad de que el flujo de trabajo que lo genera automáticamente pudiera fallar, ya que no se podía probar hasta que se creara una release. Este problema se resolverá en el Sprint 3.

Sprint 2 Changelog

---

.github/workflows/django.yml
sonar-project.properties

Se han realizado ajustes en los flujos de trabajo de GitHub Actions para generar informes de cobertura de código y vincularlos con SonarCloud.
Si bien la herramienta **coverage** estaba ya puesta en requierements.txt previamente, asegurate de tenerla instalada, ya que el requierements se va actualizando por los compañeros de cuando en cuando. Haz **pip install -r requirements.txt**
**Please, don't forget to close #178**

fix: SonarCloud coverage include

---

banquetBuddy/catering_employees/tests.py

Se han reducido las lineas de código en los tests de catering_employee, eliminando lineas innecesarias, así
como unificando el setup de los tests para eliminar todo el código repetido
Closes #186

Fix/186 f 001 refactorizar tests catering employees #186

---

banquetBuddy/populate_db.py

Se ha poblado la base de datos con 2 cuentas de administrador,con el fin de poder acceder a la consola de administrador sin necesidad de crear un superusuario en local
Incluye cualquier contexto relevante o información adicional para probar los cambios realizados en la rama.
Probar que el fichero de población(populate_db.py) funciona y que se pueda entrar a la consola de administrador con las dos cuentas de administrador

feature:populate db with superusers

---

banquetBuddy/core/templates/core/actual_privacy_policy.html
banquetBuddy/core/templates/core/actual_terms_and_conditions.html
banquetBuddy/core/templates/core/politicas y terminos anteriores/policyv1_0.html
banquetBuddy/core/templates/core/politicas y terminos anteriores/termsv1.0.html
banquetBuddy/core/templates/core/previous_policies.html
banquetBuddy/core/templates/core/previous_terms.html
banquetBuddy/core/urls.py
banquetBuddy/core/views.py

Según la pildora GDPR se priorizaron los siguientes puntos:
**Términos Claros:**
Claridad en la Comunicación en general en todos los apartados y aparte
- Sección 1 - Introducción para información general
-  Sección 2 "Aceptación de la Política" (Consentimiento Informado)
- Sección 3 - Cambios en la Política de Privacidad para saber cómo se cambia la Politica y qué consecuencias tiene.
- Aparte viene la versión de la Politica y fecha de entrada en vigor para proporcionar aún más claridad al usuario.
**Garantía de Privacidad:**
- Política de Privacidad, Sección 9 "Seguridad de los Datos".
**Plan de Contingencia:** 
- Política de Privacidad, Sección 11 "Procedimiento en Caso de Violación de Datos".
**Derecho al Olvido:**
- Política de Privacidad, Sección 8 "Derechos de los Usuarios". …

feature: Privacy Policy and Terms improved

---

banquetBuddy/catering_employees/templates/employee_offer_list.html
banquetBuddy/catering_employees/templatetags/custom_tags.py
banquetBuddy/catering_employees/tests.py
banquetBuddy/catering_owners/forms.py
banquetBuddy/catering_owners/models.py
banquetBuddy/catering_owners/templates/applicants_list.html
banquetBuddy/catering_owners/templates/hire_form.html
banquetBuddy/catering_owners/templates/list_employee.html
banquetBuddy/catering_owners/templates/offers/create_offer.html
banquetBuddy/catering_owners/templates/offers/edit_offer.html
banquetBuddy/catering_owners/templates/offers/offer_list.html
banquetBuddy/catering_owners/tests.py
banquetBuddy/catering_owners/urls.py
banquetBuddy/catering_owners/views.py
banquetBuddy/catering_particular/views.py
banquetBuddy/core/tests.py
banquetBuddy/populate_db.py

Con el fin de mejorar la experiencia de usuario se han realizado varios cambios en la aplicación:
1) a la hora de crear la oferta es el empresario quién pone las fechas de trabajo
2) a la hora de aplicar a la oferta, el empleado es infromado de las fechas de su trabajo, así como se le pide confirmación adiconal para que aplique a una oferta
3) el empresario a la hora de contratar o rechazar realiza confirmación adicional para eviatar errores a la hora de pinchar los botones.
4) la contratación ya no requiere especificar las fechas, ya que estas son cogidas de la oferta
5) se ha agregado la paginación en la vista de empleados que pertenecen a un servicio
6) se ha aregado un filtro en la vista mencionada en el punto anterior para ver los empleados activos y los que ya no están en la empresa …

Fix/improve offer and hiring#213

---

banquetBuddy/catering_owners/forms.py
banquetBuddy/catering_owners/models.py
banquetBuddy/catering_owners/templates/edit_employee.html
banquetBuddy/catering_owners/templates/list_employee.html
banquetBuddy/catering_owners/templates/offers/create_offer.html
banquetBuddy/catering_owners/templates/offers/edit_offer.html
banquetBuddy/catering_owners/urls.py
banquetBuddy/catering_owners/views.py
banquetBuddy/core/models.py
banquetBuddy/core/templates/core/actual_privacy_policy.html
banquetBuddy/populate_db.py

Actualmente tenemos un filtrado en la vista de empleados que pertencen a un servicio que filtra por 2 estados: "Activo" y "Terminado". La lógica es la siguiente: si la fecha fin es anterior a la de hoy, el estado es "Terminado", en otro caso "Activo". Con esta pull request se introduce una novedad: un botón "modify" que permite cambiar la fecha fin de trabajo, así como especificar la causa (implementado como enumerado) y opcionalmente una descripción de lo sucedido.
Con esto:
1) Si cambio en el nuevo formulario la fecha de fin a hoy y especifico la causa (obligatorio), se entiende que el empleado está inmediatamente despedido y el estado cambia a Terminado.
2)  Si cambio en el nuevo formulario la fecha de fin a cualquier fecha posterior a hoy y especifico la causa (obligatorio), se …

Feature/dismiss employee#218

---

banquetBuddy/catering_employees/forms.py
banquetBuddy/catering_owners/forms.py
banquetBuddy/catering_owners/tests.py
banquetBuddy/catering_particular/templates/book_edit.html
banquetBuddy/catering_particular/templates/booking_process.html
banquetBuddy/catering_particular/templates/my_books.html
banquetBuddy/catering_particular/tests.py
banquetBuddy/catering_particular/urls.py
banquetBuddy/catering_particular/views.py
banquetBuddy/core/templates/core/base.html

Se ha arreglado los tests correspondientes a la funcionalidad de reservar caterings, la selección de los menús, así como la funcionalidad de 'Edit' y 'Cancel'.
No aplica

[Fix] Event Booking

---

banquetBuddy/banquetBuddy/settings.py

Se ha resuelto el problema con settings.py en local. El chat con empresa no da problemas 500.
Es importante resetear la base de datos en local, arrancar la app y entrar como empresa para comprobar el chat. He probado también enviar como particular un mensaje a una empresa y todo va sin problema, la empresa lo recibe.

fix: Settings problem solve

---

changelogs/3.0.0/CHANGELOG.md

Changelog de commits del Sprint 3
Incluye cualquier contexto relevante o información adicional para probar los cambios realizados en la rama.

doc: Add Sprint 3 commit changelog

---

banquetBuddy/catering_owners/views.py

Se ha arreglado la funcionalidad de editar ofertas
Comprobar que ya se pueden editar ofertas y aparecen los eventos a elegir

fix: Fix edit offer not showing events

---

banquetBuddy/catering_employees/templates/contact_chat_employee.html
banquetBuddy/catering_employees/templates/list_work_services.html
banquetBuddy/catering_owners/templates/contact_chat_owner.html
banquetBuddy/catering_owners/templates/employee_record.html
banquetBuddy/catering_owners/templates/list_employee.html
banquetBuddy/catering_owners/templates/manage_tasks.html
banquetBuddy/catering_owners/templates/reservations.html
banquetBuddy/catering_particular/templates/booking_process.html
banquetBuddy/catering_particular/templates/catering_review.html
banquetBuddy/catering_particular/templates/contact_chat.html
banquetBuddy/catering_particular/templates/listar_caterings.html
banquetBuddy/core/templates/core/base.html
banquetBuddy/core/templates/core/home.html
banquetBuddy/core/templates/core/login.html

Mejora de estilos en ciertas páginas y arreglo de estilos responsivos, además de que ahora es posible desde un teléfono móvil de rotar el logo de la página.
Para los estilos responsivos probar la aplicación en formato móvil.

feat: Improve styles and responsive styles fixed

---

banquetBuddy/catering_particular/views.py
banquetBuddy/core/templates/core/base.html
banquetBuddy/core/templates/core/subscriptionsplans.html

Funcionalidad para particulares subscritos que descuenta un 5% del precio de las contrataciones de catering.
También se ha añadido el frontend para la vista de los planes de subscripciones y la entrada en la navbar.

Feature/particular subscription plan#183

---

banquetBuddy/catering_employees/views.py
banquetBuddy/catering_owners/templates/list_menus.html
banquetBuddy/catering_owners/templates/list_my_services.html
banquetBuddy/catering_owners/views.py
banquetBuddy/catering_particular/templates/book_edit.html
banquetBuddy/catering_particular/templates/listar_caterings.html
banquetBuddy/catering_particular/test_selenium.py
banquetBuddy/catering_particular/tests.py
banquetBuddy/catering_particular/views.py
banquetBuddy/core/tests.py

Se han mejorado funcionalidades existentes:
1. En cuanto a los servicios:
- Para los particulares, solo se les muestre un servicio en el listado si este tiene al menos un menú asociado.
- Para los catering owners, les aparece una alerta indicando que si crea un servicio sin asociarle un menú, el servicio no será visible para los particulares.
2. En cuanto a las reservas de un catering:
- Los particulares puedan modificar únicamente la fecha del evento, una vez hecho el pago.
No procede.
Closes #292

F-010: Resolver problemas del S3

---

banquetBuddy/core/templates/core/base.html

Arregla el navbar de particular. Ahora se ven los planes.

fix: Navbar Particular

---

banquetBuddy/catering_employees/tests.py
banquetBuddy/catering_employees/views.py
banquetBuddy/catering_owners/forms.py
banquetBuddy/catering_owners/templates/list_employee.html
banquetBuddy/catering_owners/templates/manage_tasks.html
banquetBuddy/catering_owners/templates/reservations.html
banquetBuddy/catering_owners/views.py
banquetBuddy/catering_particular/tests.py
banquetBuddy/populate_db.py

1) Ahora solo las empresas que tienen PREMIUM o PREMIUM PRO podrán acceder a la funcionalidad de gestión de tareas
2) Paginación en la lista de empleados(con estado "terminated") arreglada
3) Validación relativa  a las fechas a la hora de UPDATE una tarea
4) Comentados los tests que fallaban para poder acceder de nuevo a la cobertura de Sonar
5) Accesos no autorizados a la gestión de tareas controlados
1) Para probarlo basta con entrar como cualquier empresa, hacer downgrade del plan si ya tiene uno, acceder a  management -> my bookings -> elegir un servicio de catering y en la tabla de eventos que aparece debería salir algo así: 
También se ha restringido acceso en el backend para evitar acceso a través de la URL, dado que si intenta saldrá un mensaje:
2) Para eso entramos como cualquier …

Fix/minor catering management#306

---

banquetBuddy/catering_employees/tests.py
banquetBuddy/catering_owners/tests.py
banquetBuddy/catering_particular/tests.py
requirements.txt

Se corrigen tests para que el Actions se ejecute correctamente.
No procede.

Fix: tests
